# PostgreSQL configuration template
# This file will be copied to config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "app_name_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "app_name_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "app_name_production") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5432") %>
